[package]
name = "layouts"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getset = "0.1.1"
pretty = "0.10.0"
tycho = "0.1.2"
